title: Chev Eldrid
email: chev424@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Chev Eldrid's Personal Website and blog
url: "cheveldrid.github.io" # the base hostname & protocol for your site, e.g. http://example.com
# Build settings
plugins:
  - jekyll-feed

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
